name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: cmake . && make
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: xp58tool
          path: xp58tool